version: "3.9"

services:
  app:
    build: .
    container_name: backend_app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 8000:8000

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  # pytest:
  #   image: python:3.11-slim
  #   container_name: pytest_container
  #   depends_on:
  #     - db
  #     - app
  #   working_dir: /app
  #   command: ["pytest", "-v"]
