[tool.ruff]
exclude = [
    "venv/**",
    ".venv/**",
    ".mypy_cache/**",
    ".pytest_cache/**",
    ".vscode/**",
    "**/__pycache__/**",
    "./ruff_cache/**",
    "./Dockerfile",
    "./docker-compose.yml",
    "./docker/**",
    "./req.txt",
    "./test.py",
    "./test12.py",
]


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["E722"]

fixable = ["ALL"]
unfixable = []



